-- Fix contaminated descriptions: 10 Kingston records mentioning Portland
-- Run in Supabase Studio SQL editor (requires service role or rls bypass)
-- Generated by scripts/fix-contaminated-descriptions.ts

UPDATE restaurants SET
  description        = 'Mapped jerk spot in Barbican, Kingston. Public signals are shown where available, and WhenWiHungry verdicts are added as reviews go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = '22-jerk-plus';

UPDATE restaurants SET
  description        = 'Mapped café and light bites spot in Constant Spring, Kingston. Public signals are shown where available, and WhenWiHungry verdicts are added as reviews go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'cafe-dolce';

UPDATE restaurants SET
  description        = 'Mapped food spot in Kings House Rd, Kingston. Public signals are shown where available, with critic verdicts added as they go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'idcove-catering';

UPDATE restaurants SET
  description        = 'Mapped bar and drinks spot in Lindsay Crescent, Kingston. Public signals are shown where available, and WhenWiHungry verdicts are added as reviews go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'jamaica-liquor-warehouse';

UPDATE restaurants SET
  description        = 'Mapped jerk spot in Hope Rd, Kingston. Public signals are shown where available, and WhenWiHungry verdicts are added as reviews go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'jerk-box';

UPDATE restaurants SET
  description        = 'Mapped seafood spot in Lindsay Crescent, Kingston. Details, public signals, and critic verdicts are added as the listing is verified.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'king-janga-seafood-lounge';

UPDATE restaurants SET
  description        = 'Mapped jerk spot in Chelsea Ave, Kingston. Public signals are shown where available, and WhenWiHungry verdicts are added as reviews go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'kingston-jerk';

UPDATE restaurants SET
  description        = 'Mapped food spot in Constant Spring, Kingston. Public signals are shown where available, with critic verdicts added as they go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'market-place';

UPDATE restaurants SET
  description        = 'Mapped café and light bites spot in South Ave, Kingston. Public signals are shown where available, and WhenWiHungry verdicts are added as reviews go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'susies';

UPDATE restaurants SET
  description        = 'Mapped food spot in Annette Cres, Kingston. Public signals are shown where available, with critic verdicts added as they go live.',
  data_quality_status = 'corrected',
  description_status  = 'conflict_fixed',
  location_notes      = 'Description previously mentioned Portland but parish/address indicates Kingston. Corrected by data cleanup script.'
WHERE slug = 'triple-tz-eatery';

-- Verify: should return 0 rows after successful run
SELECT slug, name, description
FROM restaurants
WHERE parish = 'Kingston'
  AND description ILIKE '%portland%';
